### ISSUE TITLE
Please update with latest version 2.0.19.

### ISSUE THREAD

**Issue by rvpatel** [wp-premium/woocommerce-subscriptions#1]
Please update with latest version 2.0.19.

**Comment by remcotolsma** [comment]
> WooCommerce Subscriptions, Git-ified. Synced manual! This repository is just a mirror of the WooCommerce Subscriptions plugin. Please do not send pull requests and issues.

https://github.com/wp-premium/woocommerce-subscriptions/tree/2.0.19
