### ISSUE TITLE
Can i Start with 0 initial without trail month?

### ISSUE THREAD

**Issue by atiqrahmanfeni** [wp-premium/woocommerce-subscriptions#11]
Hi,

Can i Start with 0 amount initial payment without trail month?

i want user will start with 0 deposit once i have made delivered product than 1st invoice will generate with current month prorate amount. then every month 1st will pay full amount of subscription.

How can i achieve this?

thank you

**Comment by remcotolsma** [comment]
Unfortunately I don't have the answer to that, this repository is also mainly a mirror for https://woocommerce.com/products/woocommerce-subscriptions/. For questions I would contact via https://woocommerce.com/contact-us/.
