### ISSUE TITLE
WooCommerce legacy customers API broken - v2 and v3

### ISSUE THREAD

**Issue by rfink** [wp-premium/woocommerce-subscriptions#2]
Hello,

This plugin breaks the WooCommerce legacy API (WC version 2.6.x) for v2 and v3 for the /customers endpoint. By using this line (31 in includes/api/class-wc-api-subscriptions-customers.php):

```
remove_action( 'pre_user_query', array( $this, 'modify_user_query' ) );
```

Which removes the additional filtering for created_at_min and created_at_max.  When pulling data from the /customers endpoint and using those parameters as query strings, the full set of customers is always returned regardless.  Please advise.

Thanks!

**Comment by remcotolsma** [comment]
> WooCommerce Subscriptions, Git-ified. Synced manual! This repository is just a mirror of the WooCommerce Subscriptions plugin. **Please do not send pull requests and issues.**

https://www.woocommerce.com/my-account/tickets/

**Comment by rfink** [comment]
Hello,

It appears that one has to be a paying customer in order to file a technical ticket. Our company is not a consumer of WooCommerce, we are a 3rd party integration and analytics service that serves several hundred customers by consuming the API. What options are available to us?
